apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: kubeEtcd.service.targetPort
          value: "2381"
